[package]
name = "mcloudtt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.18.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
futures-util = "0.3.25"
mqtt-v5 = "0.1.1"
bytes = "0.5.6"