[general]
websocket = true
timeout = 30

[tls]
certfile = "certs/server.crt"
keyfile = "certs/server.key"

[ports]
tcp = 1883
ws = 8080

[bigquery]
project_id = "your-project-id"
dataset_id = "mcloudttbq"
table_id = "topic-log"
credentials_path = "sa.key"

[redis]
host = "redis"
port = 6379