[package]
name = "demo_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
chrono = "0.4.23"
paho-mqtt = "0.12.0"
clap = { version = "4.1.4", features = ["derive"] }
